### ISSUE TITLE
Error starting transactor

### ISSUE THREAD

**Issue by kidpollo** [pointslope/docker-datomic-example#11]
> java.lang.RuntimeException: Unable to load license key*

I get this error when doing `docker-compose up` I have the creds and the license in the config files. The error details dont say much else.

![docker-datomic zsh 2017-07-21 12-24-18](https://user-images.githubusercontent.com/8182/28479022-8d75c90e-6e0f-11e7-80df-91543da77d8e.png)

Have you encountered this before?

**Comment by christianromney** [comment]
Only when someone doesn't complete steps 2. or 3. of the README exactly. Also could be any line breaks the were accidentally entered when copying and pasting the license key. Could you verify that it's all on one line (editor wrapping is OK).

**Comment by kidpollo** [comment]
You are right. The lisence copied from my email client had weird invisible chars 👍
