### ISSUE TITLE
DynamoDB AWS credentials?

### ISSUE THREAD

**Issue by luposlip** [pointslope/docker-datomic-example#4]
Hi there!

Seems like I have both docker images started by `docker-compose run`.

I've changes the transactor properties to point to DynamoDB, and added my AWS credentials as ENV lines in the 2 `Dockerfile`s like this:

```
FROM pointslope/datomic-pro-starter:0.9.5344
ENV AWS_ACCESS_KEY_ID [SEMI SECRET ACCESS KEY]
ENV AWS_SECRET_KEY [SUPER SECRET SECRET KEY]
CMD ["config/transactor-ensured.properties"]
ADD restore-db.sh /usr/local/bin/restore-db
```

The console container starts up nicely, but the transactor can't find it's credentials:

```
Starting datomic:ddb://eu-central-1/data/<DB-NAME> ...
datomicdb_1 | System started datomic:ddb://eu-central-1/data/<DB-NAME>
datomicdb_1 | Critical failure, cannot continue: Lifecycle thread failed
datomicdb_1 | java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
[...]
```

Do you have an example of a Dockerfile where you connect to DynamoDB?

Thanks in advance (and sorry if there was somewhere else I should've posted my question)!

Best,
Henrik

**Comment by luposlip** [comment]
In a side note, I got the same transactor - with the same credentials and Dockerfile - up and running the first time a tried, following your guide from https://hub.docker.com/r/pointslope/datomic-pro-starter/.
(I'm a newbie to Docker, and haven't used docker-compose before)

**Comment by christianromney** [comment]
Hi Henrik,

Sorry for the delay responding. Glad you seem to have gotten it working. How's your experience been? Did this work pointing to Dynamo? 

Cheers,
Christian

**Comment by luposlip** [comment]
Hi Christian,

No worries.
No, actually I ended up using your plain pointslope/clojure:lein-2.5.3, and then adding what I needed from there.
But eventually I got Datomic up and running, connecting to Dynamo.

I used the little trick that can be seen here:
**UPDATED**: https://github.com/enterlab/docker-aws-ecs-env/blob/master/start

Best,
Henrik

**Comment by christianromney** [comment]
Glad you were able to resolve everything. You might be interested to know we've recently deprecated our pointslope/clojure image in favor of the official clojure/lein-2.6.1-alpine image. We're not getting rid of the images or anything, but now that the official clojure image uses Alpine Linux we've seen a the image size reduced by HALF.

**Comment by luposlip** [comment]
Thanks for mentioning it! I'll try that immediately 😊

Den lør. 23. jul. 2016 00.56 skrev Christian Romney <
notifications@github.com>:
