### ISSUE TITLE
Wrong reference of datomic-console image in datamic-console/Dockerfile

### ISSUE THREAD

**Issue by vkuepo** [pointslope/docker-datomic-example#8]
Error while calling docker-compose-up because datamic-console/Dockerfile is referencing the wrong image.
Instead of _FROM pointslope/docker-datomic-console:0.9.5394_ should be **FROM pointslope/datomic-console:0.9.5394**

**Comment by christianromney** [comment]
Thanks. This is now fixed and bumped to the latest release (0.9.5544). Sorry for the delay.
